name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create schema.graphql from schema.ts
        run: sed 's/export const typeDefinitions = //' src/schema.ts > schema.graphql

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:schema.graphql'
          approve-label: expected-breaking-change
