name: Lint #

on:
  pull_request:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

      - name: Run prettier
        run: npx prettier --debug-check .
