name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            suffix: linux-amd64
          - os: ubuntu-latest
            arch: arm64
            suffix: linux-arm64
    name: "Release for ${{ matrix.suffix }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # ARM64 build in Docker
      - name: Build in ARM64 Docker container
        if: matrix.arch == 'arm64'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace node:18-bullseye bash -c "
            npm ci &&
            npm run build &&
            npm pack
          "

      # x64 build steps
      - name: Build and package for x64
        if: matrix.arch == 'x64'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          architecture: ${{ matrix.arch }}
      - run: |
          npm ci
          npm run build
          npm pack
        if: matrix.arch == 'x64'

      - name: Rename package with suffix
        run: |
          for file in *.tgz; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.tgz}-${{ matrix.suffix }}.tgz"
            fi
          done

      # Only one job creates the release
      - name: Create Release
        if: matrix.arch == 'x64'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *-${{ matrix.suffix }}.tgz

      # Other jobs upload their binaries to existing release
      - name: Upload Release Asset
        if: matrix.arch != 'x64'
        run: gh release upload ${{ github.ref_name }} *-${{ matrix.suffix }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}