name: Run Tests

on:
  pull_request:
  push: 
    branches: 
      - main

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: archive
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Download nightly Berkeley dump
      run: bash ./scripts/download_db.sh

    - name: Install PostgreSQL client
      run: |
        apt-get update
        apt-get install --yes postgresql-client

    - name: Create Archive Node database
      run: psql -h postgres -U postgres archive < ./data/berkeley-archive.sql
      env:
        PGPASSWORD: password

    - name: Run tests
      run: npm run test