name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install zkapp-cli
        run: npm install -g zkapp-cli

      - name: Run tests
        run: npm run test
